export const courseOptions = [
    { value: 'Introduction to SDH', label: 'Introduction to SDH' },
    { value: 'Introduction to OTN', label: 'Introduction to OTN' },
    { value: 'Introduction to DWDM', label: 'Introduction to DWDM' },
    { value: 'Introduction to LTE', label: 'Introduction to LTE' },
    { value: 'Software Architecture', label: 'Software Architecture' },
    { value: 'Introduction to SDLC', label: 'Introduction to SDLC' },
    { value: 'Introduction to Test Equipment', label: 'Introduction to Test Equipment' },
    { value: 'Introduction to Firmware', label: 'Introduction to Firmware' },
    { value: 'Overview of Diagnostics', label: 'Overview of Diagnostics' },
    { value: 'Introduction to NM', label: 'Introduction to NM' },
    { value: 'Introduction to GPON', label: 'Introduction to GPON' },
    { value: 'Introduction to TIDL', label: 'Introduction to TIDL' },
    { value: 'Basics of Scripting', label: 'Basics of Scripting' },
    { value: 'Overview of Debugging Tools', label: 'Overview of Debugging Tools' },
    { value: 'Introduction to MIB', label: 'Introduction to MIB' },
    { value: 'Introduction to HAL', label: 'Introduction to HAL' },
    { value: 'NMS Components', label: 'NMS Components' },
    { value: 'Understanding NMS Topology', label: 'Understanding NMS Topology' },
    { value: 'Virtual Devices and Drivers', label: 'Virtual Devices and Drivers' },
    { value: 'Fault Management', label: 'Fault Management' },
    { value: 'Introduction to EMS', label: 'Introduction to EMS' },
    { value: 'Introduction to NMS Administration', label: 'Introduction to NMS Administration' },
];